### ISSUE TITLE
too suspicious

### ISSUE THREAD

**Issue by laylaws** [dotcppfile/DAws#12]
Do you think you could make a version that is a little less suspicious? Remove all the comments and change the name of the files it creates?

**Comment by awnumar** [comment]
You mean obfuscate it?

**Comment by laylaws** [comment]
That and it creates a folder named DAws and inside a file named DAws.php. It doesn't delete itself either.

**Comment by dotcppfile** [comment]
That folder that DAws creates and moves itself to is its own directory where it will drop various files such as: .htaccess, php.ini, cgi shells, etc. Also, anything that the user uploads or creates will go into that directory. What I'm trying to say is that it's not just a random action; DAws is not a backdoor, it's a big gun that you use to get things done in a tidy and neat way, when you're over you just remove DAws.php, the DAws directory and that's it.
