### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by yashar6909** [dotcppfile/DAws#5]
I am testing DAws, i d love to know how to get past the fake error generated?

**Comment by ghost** [comment]
post the admin password via a custom form.

**Comment by dotcppfile** [comment]
To get past the fake error generated you need to login and to do that you need to send a post request holding the following post data: pass=DAws ("DAws" is the default password unless you changed it)
To send the post data you can do just like toby57 said (thanks for helping him out mate) or you can simply use a firefox add on like Live Http Headers, Temper Data or Hack Bar which will make life easier for you.
