### ISSUE TITLE
Error After Uploading

### ISSUE THREAD

**Issue by jhayssika** [dotcppfile/DAws#9]
Help!!!
am getting an error 404 after uploading DAWS files..
Not Found
The requested URL .../DAws.php was not found on this server.
Apache/2 at Port 80

Please what could be wrong??

**Comment by dotcppfile** [comment]
Are you getting this error after you upload DAws or after you use DAws to upload a file?

**Comment by jhayssika** [comment]
am getting the error after uploading Daws.

**Comment by dotcppfile** [comment]
That's the fake 404 page, you need to send the following post data to DAws.php "pass=DAws" (without the quotes) and the shell will load afterwards.

**Comment by jhayssika** [comment]
i still get the Error 404 with this "**http://..../xyz/DAws.php?pass=DAws**"

**Comment by awnumar** [comment]
That's a GET request fam. If you can't tell the difference, you probably shouldn't be using a webshell.

**Comment by jhayssika** [comment]
- [ ] ..After posting data.. i get a 500 Internal Server Error, but .../old_daws/DAws.php is working alright.

- [ ] When i try to upload a file or create a folder, i get an error 404 Not Found.

Please kindly help your girl out..
